apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info
  labels:
    app: devops
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-app
        image: isakimov/devops-info:1.0
        ports:
        - containerPort: 80
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: default
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  serviceAccountName: default
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: internal-nginx
  namespace: default
spec:
  controller: nginx.org/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
annotations:
  kubernetes.io/ingress.class: "nginx"
metadata:
  name: ingress-test
  namespace: default  
spec:
  ingressClassName: internal-nginx
  rules:
   - host: devops-info.com
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: devops-service
                port: 
                  number: 80
