apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info
  labels:
    app: devops
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-app
        image: isakimov/devops-info:1.0
        ports:
        - containerPort: 80
      serviceAccountName: default
