apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info
  labels:
    app: devops
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-app
        image: isakimov/devops-info:1.0
        ports:
        - containerPort: 80
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: default
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
  type: NodePort
  serviceAccountName: default
