- hosts: localhost
  become: yes
  remote_user: root

  tasks:
   - name: Creates directory
     file:
       path: /home/test_akimov
       state: directory
       
   - name: Clone git to a local server
     git:
       repo: https://github.com/isakimov/test_akimov.git
       dest: /home/test_akimov/
       
   - name: Build image and with build args
     community.docker.docker_image:
       name: devops-info
       build:
         path: /home/test_akimov
         args:
           log_volume: /var/log/myapp
           listen_port: 80
       source: build

   - name: Login DockerHub
     community.docker.docker_login:
       username: isakimov
       password: 089769700dD

   - name: Tag and push to DockerHub
     community.docker.docker_image:
       name: devops-info
       repository: isakimov/devops-info:1.0
       push: true
       source: local

   - name: Create a Deployment
     kubernetes.core.k8s:
       state: present
       src: /home/test-akimov/deployment-service-ingress.yml
