 hosts: localhost
  become: yes
  remote_user: root
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

  tasks:
   - name: Creates directory
     file:
       path: /home/test_akimov
       state: directory

   - name: Creates directory for Jenkins
     file:
       path: /var/jenkins_home
       state: directory
       owner: "{{ username }}"
       mode: 777
       recurse: yes

   - name: Creates directory for Nexus
     file:
       path: /home/nexus/data/nexus-data
       state: directory
       owner: "{{ username }}"
       mode: 777
       recurse: yes

   - name: Clone git to a local server
     git:
       repo: https://github.com/isakimov/test_akimov.git
       dest: /home/test_akimov/

   - name: Deploy jenkins and nexus
     community.docker.docker_compose:
       project_src: /home/test_akimov
       files:
       - docker-compose.yaml

