- hosts: localhost
  become: yes
  remote_user: root

  tasks:
   - name: Creates directory
     file:
       path: /home/test_akimov
       state: directory

   - name: Creates directory for Jenkins
     file:
       path: /var/jenkins_home
       state: directory
       mode: 0777
       recurse: yes

   - name: Creates directory for Nexus
     file:
       path: /home/nexus/data/nexus-data
       state: directory
       mode: 0777
       recurse: yes

   - name: Clone git to a local server
     git:
       repo: https://github.com/isakimov/test_akimov.git
       dest: /home/test_akimov/

   - name: Deploy jenkins and nexus
     community.docker.docker_compose:
       project_src: /home/test_akimov
       files:
       - docker-compose.yaml

   - name: Build image and with build args
     community.docker.docker_image:
       name: devops-info
       build:
         path: /home/test_akimov
         args:
           log_volume: /var/log/myapp
           listen_port: 80
       source: build
