- hosts: localhost
  become: yes
  remote_user: root

  tasks:
   - name: Creates directory
     file:
       path: /home/test_akimov
       state: directory

   - name: Creates directory for Jenkins
     file:
       path: /var/jenkins_home
       state: directory
       mode: 0777
       recurse: yes

   - name: Creates directory for Nexus
     file:
       path: /home/nexus/data/nexus-data
       state: directory
       mode: 0777
       recurse: yes

   - name: Clone git to a local server
     git:
       repo: https://github.com/isakimov/test_akimov.git
       dest: /home/test_akimov/

   - name: Deploy jenkins and nexus
     community.docker.docker_compose:
       project_src: /home/test_akimov
       files:
       - docker-compose.yaml

   - name: Build image and with build args
     community.docker.docker_image:
       name: devops-info
       build:
         path: /home/test_akimov
         args:
           log_volume: /var/log/myapp
           listen_port: 80
       source: build

   - name: Disable Jenkins authorization
     community.docker.docker_container_exec:
       container: jenkins
       command: /bin/bash -c "sed -i 's/<useSecurity>true<\/useSecurity>/<useSecurity>false<\/useSecurity>/g' /var/jenkins_home/config.xml"
       chdir: /var/jenkins_home

   - name: Jenkins pass
     community.docker.docker_container_exec:
       container: jenkins
       command: /bin/bash -c "cat /var/jenkins_home/secrets/initialAdminPassword"
     register: jenkins_pass

   - name: Nexus pass
     community.docker.docker_container_exec:
       container: nexus3
       command: /bin/bash -c "cat /nexus-data/admin.password"
     register: nexus_pass

   - name: Print Nexus pass
     debug:
       var: jenkins_pass.stdout

   - name: Print Nexus pass
     debug:
       var: nexus_pass.stdout

   - name: Log into DockerHub
     community.docker.docker_login:
       username: isakimov
       password: 089769700dD

   - name: Tag and push to DockerHub
     community.docker.docker_image:
       name: devops-info
       repository: isakimov/devops-info:1.0
       push: true
       source: local

   - name: Create container devops-info
     community.docker.docker_container:
       name: devops-info
       image: isakimov/devops-info:1.0
       ports:
        - 8082:80
